image: gradle:eclipse-temurin:21

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/caches/
    - .gradle/wrapper/

build:
  stage: build
  script:
    - ./gradlew clean compileJava --no-daemon

test:
  stage: test
  script:
    - ./gradlew test --no-daemon
