import org.codehaus.groovy.tools.shell.util.Logger.io
import org.gradle.internal.impldep.org.bouncycastle.pqc.math.linearalgebra.PolynomialRingGF2.rest

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.testng)
//    implementation(libs.org.seleniumhq.selenium.selenium.java)
//    implementation(libs.io.github.bonigarcia.webdrivermanager)
    implementation(libs.guava)
    implementation(libs.playwright)
    testImplementation(libs.restassured)
}

group = "io.github.densudas"
version = "1.0-SNAPSHOT"
description = "automation-testing-framework"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG()
}
