/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.testng)
    implementation(libs.selenium)
    implementation(libs.webdrivermanager)
    implementation(libs.guava)
    implementation(libs.playwright)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.rest.assured)
}

group = "io.github.densudas"
version = "1.0-SNAPSHOT"
description = "automation-testing-framework"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
